packaging_format = 2

id = "kbin"
name = "Kbin"
description.en = "Decentralized content aggregator and microblogging platform"
description.fr = "Agrégateur de contenu décentralisé et plateforme de microblogging"
description.es = "Agregador de contenido descentralizado y plataforma de microblogging"

version = "1.0~ynh1"

maintainers = ["csolisr@gmail.com"]

[upstream]
license = "AGPL-3.0"
website = "https://kbin.pub"
demo = "https://kbin.social"
admindoc = "https://codeberg.org/Kbin/kbin-core/wiki#user-content-admin-guide"
userdoc = "https://codeberg.org/Kbin/kbin-core/wiki#user-content-user-guide"
code = "https://codeberg.org/Kbin/kbin-core"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "256M"
ram.build = "512M"
ram.runtime = "512M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kbin"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    ask.es = "Elija el idioma de la aplicación"
    type = "string"
    choices = ["fr", "en", "es"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.federate]
    ask.en = "Do you want this instance to enable federation?"
    ask.fr = "Voulez-vous que cette instance ait la fédération activée?"
    ask.es = "¿Desea que esta instancia active la federación?"
    type = "boolean"
    default = true

    [install.register]
    ask.en = "Do you want this instance to have open registration?"
    ask.fr = "Voulez-vous que cette instance ait un enregistrement ouvert?"
    ask.es = "¿Desea que esta instancia tenga registros abiertos?"
    type = "boolean"
    default = false

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://codeberg.org/Kbin/kbin-core/archive/edb4380fa26eef709b36f1014853d796b28a79d0.tar.gz"
        sha256 = "70313a9503ae2782e84d4f4a0a24fc6a29de1d2eea5d65463348dbcba870ff04"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, postgresql-contrib, php8.2-common, php8.2-fpm, php8.2-cli, php8.2-amqp, php8.2-pgsql, php8.2-gd, php8.2-curl, php8.2-simplexml, php8.2-dom, php8.2-xml, php8.2-redis, php8.2-intl, unzip, php-symfony-console, php-symfony-mercure"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
    
    extras.symfony_cli.repo = "deb https://dl.cloudsmith.io/public/symfony/stable/deb/debian bullseye main"
    extras.symfony_cli.key = "https://dl.cloudsmith.io/public/symfony/stable/gpg.99CEF8A62216B73D.key"
    extras.symfony_cli.packages = "symfony-cli"

    [resources.database]
    type = "postgresql"
