test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.federate = true
    args.register = false

   